# Generated by Django 4.0 on 2022-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('reminder', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
